### ISSUE TITLE
compute strength explicitly

### ISSUE THREAD

**Issue by ThomasWaldmann** [lichtkegel/aestools#12]
https://github.com/lichtkegel/aestools/blob/master/src/aestools/checkkey.py#L65

it uses the given threshold T there, computes 2^T and checks if group_order is bigger than that, giving the boolean "is it safe" result.

more interesting could be to compute the log2(group_order) so we can actually show how safe a given key is?

@lichtkegel what do you think, does that make sense and can it be implemented easily?

if so, there could be an inner function that computes bit strength, and the "is it safe" function would just call that and compare to the threshold.

**Comment by huettenhain** [comment]
Actually, I just searched around a bit and it seems like the [`bit_length()`](https://docs.python.org/3/library/stdtypes.html#int.bit_length) function is exactly what we need. It is in Python >=2.7 and >=3.1, which is fine by me. If you agree that using that is ok, I will implement it as you suggested.

**Comment by ThomasWaldmann** [comment]
that will only give integer results. so there will be nothing between e.g. 6 and 7.

**Comment by lichtkegel** [comment]
Alright. We can do this with "normal" floating point logarithms, It handles any number that can come out of this quite well.

``` 
>>> from math import log
>>> log(1<<128, 2)
128.0
>>> log(1<<128 + 1, 2)
129.0
```

**Comment by huettenhain** [comment]
The problem is that you cannot get much more with normal floating point logarithms, because even a double precision float has only 52 bits mantissa. Hence, you will get behaviour like this:

```
>>> from math import log
>>> log( (1<<112) + (1<<40), 2)
112.0
>>> log( (1<<112) + (1<<20), 2)
112.0
>>> log( (1<<112) + (1<<12), 2)
112.0
>>> log( (1<<52) + (1<<12), 2)
52.00000000000131
```

All the same, unless you get closer to 52. But our values will be larger than 100 usually, so that's no good.

**Comment by ThomasWaldmann** [comment]
Ignore me, i was confused. It will give integer values from 0 .. 127, which is fine.

**Comment by ThomasWaldmann** [comment]
hmm, it doesn't give 128 iirc. is that correct or are we off by one?

**Comment by huettenhain** [comment]
You are right, but `n.bit_length()-1` is equal to `floor(log(n,2))`. Since we want `(1<<96) + 1` to have bit strength of `96`, this sounds like the right value to compute.

```
>>> from math import floor, ceil, log
>>> all( n.bit_length()-1 == floor(log(n,2)) for n in range(1,(1<<20)))
True
```

Furthermore:

```
>>> all( (n >= (1<<m)) == (n.bit_length()-1 >= m) for n in range(1,(1<<10)) for m in range(11) )
True
```

it does compute the value that is of interest for [line 65 in checkkey.py](https://github.com/lichtkegel/aestools/blob/master/src/aestools/checkkey.py#L65).

**Comment by ThomasWaldmann** [comment]
ok. do you implement it?

**Comment by huettenhain** [comment]
Yep, will do.

**Comment by huettenhain** [comment]
Has been implemented, tests go through.
https://github.com/lichtkegel/aestools/blob/master/src/aestools/checkkey.py

**Comment by ThomasWaldmann** [comment]
ok, closing. followup (add tests) in #14.
