### ISSUE TITLE
bit length question

### ISSUE THREAD

**Issue by ThomasWaldmann** [lichtkegel/aestools#3]
This somehow seems to refer to 128bit keys (and making sure they have more than 126bits of security):

https://github.com/lichtkegel/WeakAESGCM/blob/master/check_weak_aes_gcm_key.py#L41

But here it is feeding it with 256bit keys (and still checking for >= 126bits of security):
https://github.com/lichtkegel/WeakAESGCM/blob/master/check_weak_aes_gcm_key.py#L65

Is this a bug or can you explain why it makes sense?

**Comment by huettenhain** [comment]
I can explain why this makes sense. The weakness described in [the paper](https://eprint.iacr.org/2011/202.pdf) is against the authentication in GCM. The strength of the authentication tag of GCM is _at most 128 bit_, because the tag is a 128 bit value computed inside a finite field of size 2^128. The size of the AES key has no influence on this, it is inherent to GCM. See also [the wikipedia page on GCM](https://en.wikipedia.org/wiki/Galois/Counter_Mode#Security), second paragraph.

**Comment by ThomasWaldmann** [comment]
thanks for the explanation, I added it to the docstring in the latest PR.
