### ISSUE TITLE
fix setup.py metadata

### ISSUE THREAD

**Issue by ThomasWaldmann** [lichtkegel/aestools#6]
https://github.com/lichtkegel/WeakAESGCM/blob/master/setup.py#L13

there are some placeholders that need to be filled in before a release on pypi can be made.

so @lichtkegel, do you want to be maintainer for this package?
shall I do it?

**Comment by huettenhain** [comment]
I can be package maintainer, no problem. One question, what does the `py_modules` parameter in `setup.py` do? I can't find it in the docs. I mean, the name is telling but I am unsure about its purpose. Furthermore, I'd like to choose a less generic name than `weakkey` for the module because the functionality is quite specific to AES GCM. Ideas? The name `weakaesgcmkey` is quite terrible.

**Comment by huettenhain** [comment]
I updated the [`setup.py`](https://github.com/lichtkegel/WeakAESGCM/blob/master/setup.py#L13) with some preliminary changes.

**Comment by ThomasWaldmann** [comment]
I just copied the py_modules thing from another setup.py. I am still working on creating a more sane project structure and setup.py, PR for that will come soon.

Also, I am thinking about renaming to aestools or so (it's not just about detecting weak keys, but also about finding non-weak ones).

**Comment by huettenhain** [comment]
Thumbs up for _aestools_. Still a bit pretentious, but let's just say there's an option to add more features in the future.

**Comment by ThomasWaldmann** [comment]
done.
